const ALERT  = "ALert"
const REFECTCH_CHATS  = 'REFECTCH_CHATS'
const NEW_ATTACHMENTS = 'NEW_ATTACHMENTS'
const NEW_MESSAGE_ALERT = 'NEW_MESSAGE_ALERT'
const NEW_REQUEST = 'NEW_REQUEST'
const NEW_MESSAGE = 'NEW_MESSAGE'
const START_TYPING = "START_TYPING"
const STOP_TYPING = "STOP_TYPING"

const CHAT_JOINED = "CHAT_JOINED"
const CHAT_LEAVE = "CHAT_LEAVE"
const ONLINE_USERS = "ONLINE_USERS"
export {ALERT,REFECTCH_CHATS,NEW_ATTACHMENTS,NEW_MESSAGE_ALERT,NEW_REQUEST,NEW_MESSAGE,START_TYPING,STOP_TYPING,CHAT_JOINED,CHAT_LEAVE,ONLINE_USERS}